version: "3.8"

services:
  
  postgresql:
    image: postgres:13.2-alpine
    ports:
      - 5433:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      #- ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backstage:
    image: backstage
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - 7007:7007
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      BACKEND_SECRET: ${BACKEND_SECRET}
      AUTH_GITLAB_CLIENT_ID: ${AUTH_GITLAB_CLIENT_ID}
      AUTH_GITLAB_CLIENT_SECRET: ${AUTH_GITLAB_CLIENT_SECRET}
#    depends_on:
#      postgresql:
#        condition: service_healthy

volumes:
  postgresql-data: {}
